lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 10800

    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
        query_parameter:
            enabled: true
            name: bearer
        cookie:
            enabled: true
            name: auth_token

    set_cookies:
        auth_token:
            lifetime: 10
            httpOnly: true
            samesite: lax
            secure: true
