nelmio_cors:
    defaults:
        origin_regex: true
        # allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        # allow_origin: ['https://127.0.0.1:5173']
        allow_credentials: true
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Accept', 'X-Requested-With']
        expose_headers: ['Link', 'Authorization']
        max_age: 3600
    paths:
        '^/': # Appliquer les règles CORS à toutes les routes
            # allow_origin: ['https://127.0.0.1:5173']
            allow_credentials: true
