version: '3.8'

services:
  # MariaDB
  db:
    image: mariadb:latest
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    networks:
      - symfony_network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: symfony_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge
